# Generated by Django 3.2.10 on 2023-02-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admindb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('MobileNumber', models.IntegerField(blank=True, null=True)),
                ('EmailID', models.EmailField(blank=True, max_length=254, null=True)),
                ('UserName', models.CharField(blank=True, max_length=50, null=True)),
                ('Password', models.CharField(blank=True, max_length=50, null=True)),
                ('ConfirmPassword', models.CharField(blank=True, max_length=50, null=True)),
                ('Image', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
