# Generated by Django 3.2.10 on 2023-02-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0002_categorydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicledatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleType', models.CharField(blank=True, max_length=50, null=True)),
                ('ProductName', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Color', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
                ('Image', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
