# Generated by Django 3.2.10 on 2023-02-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0004_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('EmailID', models.EmailField(blank=True, max_length=50, null=True)),
                ('Number', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('VehicleDetails', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
